---
title: "quiz 6"
author: "Jiusi Li"
date: "10/13/2020"
output: html_document
---


1
```{r}
pa=0.3
pb=0.35
pc=0.35

x1=4.05
x2=3.3
x3=3.1

p1=pa*dnorm(x1,1,1)+pb*dnorm(x1,4,2)+pc*dnorm(x1,6,2)
p2=pa*dnorm(x2,1,1)+pb*dnorm(x2,4,2)+pc*dnorm(x2,6,2)
p3=pa*dnorm(x3,1,1)+pb*dnorm(x3,4,2)+pc*dnorm(x3,6,2)

pa*dnorm(x1,1,1)/p1
pb*dnorm(x2,4,2)/p2
pc*dnorm(x3,6,2)/p3
```


2
```{r}
pa=0.78
pb=0.22

x=c(1.6,3,3.2)
x1=x
x2=x

ua=c(2.2, 3, 3.3)
ub=c(7.5, 8, 8.7)

sd=2

da=dnorm(x1[1],ua[1],sd)*dnorm(x1[2],ua[2],sd)*dnorm(x1[3],ua[3],sd)
db=dnorm(x1[1],ub[1],sd)*dnorm(x1[2],ub[2],sd)*dnorm(x1[3],ub[3],sd)

p=pa*da+pb*db

pa*da/p
pb*db/p
```


3
```{r}
pa=0.14
pb=0.86

x=5

ua=4
ub=6
sd=0.6

p=pa*dnorm(x,ua,sd)+pb*dnorm(x,ub,sd)

pa*dnorm(x,ua,sd)/p
```

```{r}
pa=0.5
pb=0.5

x=5

ua=4
ub=6
sd=0.6

p=pa*dnorm(x,ua,sd)+pb*dnorm(x,ub,sd)

pa*dnorm(x,ua,sd)/p
```

```{r}
pa=0.97
pb=0.03

x=5

ua=4
ub=6
sd=0.6

p=pa*dnorm(x,ua,sd)+pb*dnorm(x,ub,sd)

pa*dnorm(x,ua,sd)/p
```


4
```{r}
pa=0.09
pb=0.5
pc=0.41

x1=2.23
x2=4.43
x3=6.68

p1=pa*dnorm(x1,3,2)+pb*dnorm(x1,5,1)+pc*dnorm(x1,6,2)
p2=pa*dnorm(x2,3,2)+pb*dnorm(x2,5,1)+pc*dnorm(x2,6,2)
p3=pa*dnorm(x3,3,2)+pb*dnorm(x3,5,1)+pc*dnorm(x3,6,2)

pa*dnorm(x1,3,2)/p1
pb*dnorm(x1,5,1)/p1
pc*dnorm(x1,6,2)/p1
```
```{r}
pa*dnorm(x2,3,2)/p2
pb*dnorm(x2,5,1)/p2
pc*dnorm(x2,6,2)/p2
```
```{r}
pa*dnorm(x3,3,2)/p3
pb*dnorm(x3,5,1)/p3
pc*dnorm(x3,6,2)/p3
```


5
```{r}
# load packages
library("mlbench")
library("tibble")
library("klaR")

# set seed 
set.seed(48890)

# simulate dataset
sim_est = as_tibble(mlbench.2dnormals(n = 100, cl = 3))

# change class names to A, B, and C
sim_est$classes = factor(dplyr::case_when(
  sim_est$classes == 1 ~ "A",
  sim_est$classes == 2 ~ "B",
  sim_est$classes == 3 ~ "C"))

# check data
sim_est


mod <- NaiveBayes(classes~., data = sim_est)
mod$apriori
mod$tables
predict(mod,data.frame(x.1=-0.06, x.2=1.29))
```


6
```{r}
# load packages
library("MASS")
library("nnet")
library("klaR")
library("mlbench")
library("tibble")

# set seed 
set.seed(42695)

# simulate dataset
sim_est = as_tibble(mlbench.2dnormals(n = 0100, cl = 4, sd = 1.5))
sim_val = as_tibble(mlbench.2dnormals(n = 1000, cl = 4, sd = 1.5))

# check data
sim_est

misclass <- function(y,yh){
  mean(y!=yh)
}

m1 = NaiveBayes(classes~., data = sim_est)
m2 = NaiveBayes(classes~., data = sim_est, prior = c(1,1,1,1)/4)
m3 = NaiveBayes(classes~., data = sim_est, prior = c(1,1,1,1)/4, usekernel=TRUE)
m4 = lda(classes~., data = sim_est)
m5 = lda(classes~., data = sim_est, prior = c(1,1,1,1)/4)
m6 = qda(classes~., data = sim_est)
m7 = qda(classes~., data = sim_est, prior = c(1,1,1,1)/4)
m8 = multinom(classes~., data = sim_est)

misclass(sim_val$classes, predict(m1,sim_val)$class)
misclass(sim_val$classes, predict(m2,sim_val)$class)
misclass(sim_val$classes, predict(m3,sim_val)$class)
misclass(sim_val$classes, predict(m4,sim_val)$class)
misclass(sim_val$classes, predict(m5,sim_val)$class)
misclass(sim_val$classes, predict(m6,sim_val)$class)
misclass(sim_val$classes, predict(m7,sim_val)$class)
misclass(sim_val$classes, predict(m8,sim_val))
```


7
```{r}
# load packages
library("nnet")
library("tibble")

# set seed 
set.seed(27791)

# "split" data
mcr_trn = as_tibble(mlbench::mlbench.2dnormals(n = 200, cl = 4))
mcr_tst = as_tibble(mlbench::mlbench.2dnormals(n =   3, cl = 4))

# check data
mcr_trn

set.seed(42)
mod = multinom(classes~., data = mcr_trn)
predict(mod,mcr_tst,type = "probs")
```


8
```{r}
# load packages
library("klaR")
library("tibble")

# set seed 
set.seed(96233)

# "split" data
nb_trn = as_tibble(mlbench::mlbench.2dnormals(n = 200, cl = 4))
nb_tst = as_tibble(mlbench::mlbench.2dnormals(n =   3, cl = 4))

# check data
nb_trn


mod = NaiveBayes(classes~., data = nb_trn, prior = c(0.49,0.01,0.48,0.02))
predict(mod, nb_tst)
```


9
```{r}
# load packages
library("nnet")
library("tibble")

# set seed 
set.seed(21275)

# "split" data
nn_trn = as_tibble(mlbench::mlbench.cuboids(n = 200))
nn_tst = as_tibble(mlbench::mlbench.cuboids(n =   3))

# check data
nn_trn

mod = nnet(classes~., data = nn_trn, size = 6, decay = 0.25)
predict(mod, nn_tst)
```


10
```{r}
# load packages
library("kernlab")
library("tibble")

# set seed 
set.seed(78946)

# "split" data
svm_trn = as_tibble(mlbench::mlbench.cuboids(n = 200))
svm_tst = as_tibble(mlbench::mlbench.cuboids(n =   3))

# check data
svm_trn

set.seed(42)
mod = ksvm(classes~., data =svm_trn, kernel = "polydot", kpar = list(degree=3, scale=0.25), prob.model=TRUE)
predict(mod, svm_tst, type = "probabilities")
```
```{r}
#10
library("kernlab")

set.seed(78946)

# "split" data
svm_trn = as_tibble(mlbench::mlbench.cuboids(n = 200))
svm_tst = as_tibble(mlbench::mlbench.cuboids(n =   3))

# check data
svm_trn
set.seed(42)
mod12 = ksvm(classes ~., svm_trn, kernel = "polydot", kpar = list(degree = 3, scale = 0.25), prob.model =TRUE)
predict(mod12, svm_tst, type="probabilities")
```

