# Notes

## Data

'age' - age in years
'sex' - sex (1 = male; 0 = female)
'cp' - chest pain type
'trestbps' - resting blood pressure (in mm Hg on admission to the hospital)
'chol' - serum cholestoral in mg/dl
'fbs' - (fasting blood sugar > 120 mg/dl) (1 = true; 0 = false)
'restecg' - resting electrocardiographic results
'thalach' - maximum heart rate achieved
'exang' - exercise induced angina (1 = yes; 0 = no)
'oldpeak' -  ST depression induced by exercise relative to rest
'slope' -  the slope of the peak exercise ST segment
'ca' -  number of major vessels (0-3) colored by flourosopy
'thal' - 3 = normal; 6 = fixed defect; 7 = reversable defect
'num' - diagnosis of heart disease (angiographic disease status)


## Process

- Read data description
- Test-train split the data
- Look at the data
- Feature engineering

- Fit a model

#  TODO

- change levels of factor variables for better understanding
- look for "hidden" missing values like a cholesterol of 0
- look into negative values of 'oldpeak'
- deal with missing data
- fit and evaluate models
   - establish baseline
   - consider moving to binary response variable
   - consider re-introducing missing data
   - consider new modeling techniques
    - some sort of linear model
    - random forest
    - some sort of boosting
  - start using cross-validation
  
# ML pipeline

- Read in the data
- Test-train split the daata
- Cross -validate within training data to evaluate many models
  - TODO: more stuff here
- Re-fit "chosen" model to entire training data
- Make predictions on test data

# ML Systems in R
- 'caret'
- 'tidymodels'
- 'mlr3'
- 'h20'